routes/admin.php
<?php

/*
  |--------------------------------------------------------------------------
  | ADMIN Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */
Route::group(['namespace' => 'Auth', 'prefix' => 'auth'], function() {
    Route::get('login', 'LoginController@showLoginForm')->name('auth.login');
    Route::post('login', 'LoginController@login')->name('auth.login');
    Route::get('logout', 'LoginController@logout')->name('auth.logout');
});

Route::group(['middleware' => 'auth.admin'], function() {
    Route::get('/', 'DashboardController@index')->name('dashboard');


    Route::resource('layanan', 'LayananController');
    Route::resource('wilayah', 'WilayahController');
    Route::resource('transaksi', 'TransaksiController');
    Route::group(['as' => 'users.', 'namespace' => 'Users', 'prefix' => 'users'], function() {
        Route::resource('admin', 'AdminController' ,[]);
        Route::resource('member', 'MemberController' ,[]);
        Route::resource('customer', 'CustomerController' ,[]);
    });
});

routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', 'HomeController@index')->name('home');
Route::get('search', 'TourController@search')->name('search');


Route::get('tour/{id}', 'TourController@detail')->name('tour');
Route::get('pesan', 'TourController@pesan')->name('pesan');
Route::post('pesan', 'TourController@proses')->name('pesan');
Route::get('pesan/bayar/{id}', 'TourController@konfirmasi')->name('bayar');
Route::post('pesan/bayar/{id}', 'TourController@bayar')->name('bayar');

Route::get('profil/pesanan', 'ProfileController@pesanan')->name('mybooking');
Route::get('profile/setting', 'ProfileController@setting')->name('mysetting');
Route::post('profile/setting', 'ProfileController@simpan')->name('save_profile');

Route::auth();
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

app/Customer.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Customer extends Authenticatable {

    use Notifiable;

    protected $table = 'customer';
    
    public $timestamps   = false;

    protected $fillable = ['nama','no_telp','email','password','alamat','tipe_id','no_id','status'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/Users/AdminController.php
<?php

namespace App\Http\Controllers\Admin\Users;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Admin;

class AdminController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {
        $search = $request->get('search');

        $models = Admin::when($search, function($query) use ($search) {
                    build_like_query($query, 'nama', $search);
                    build_or_like_query($query, 'email', $search);
                })
                ->paginate(10);

        return view('admin.users.admin.index', compact('models'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $model      = new Admin();
        
        return view('admin.users.admin.form', compact('model'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $model          = new Admin();
        
        $validator      = \Validator::make($request->all(),[
            'nama'      => 'required',
            'email'     => 'required|email|unique:admin,email',
            'password'  => 'required',
            'status'    => 'required'
        ]);
        
        if($validator->fails()){
            return redirect()->back()->withErrors($validator->errors())->withInput($request->all());
        }
        
        $model->nama    = $request->nama;
        $model->email   = $request->email;
        $model->password= bcrypt($request->password);
        $model->status  = $request->status;
        
        $model->save();
        
        \Session::flash('success', 'Berhasil menambahkan admin baru');
        return redirect()->route('admin.users.admin.edit', ['id' => $model->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $model          = Admin::findOrFail($id);
        
        return view('admin.users.admin.form', compact('model'));
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        $model          = Admin::findOrFail($id);
        
        $validator      = \Validator::make($request->all(),[
            'nama'      => 'required',
            'email'     => 'required|email',
            'status'    => 'required'
        ]);
        
        if($validator->fails()){
            return redirect()->back()->withErrors($validator->errors())->withInput($request->all());
        }
        
        $model->nama    = $request->nama;
        $model->email   = $request->email;
        
        if($request->password)
            $model->password= bcrypt($request->password);
        
        $model->status  = $request->status;
        
        $model->save();
        
        \Session::flash('success', 'Berhasil merubah data admin');
        return redirect()->route('admin.users.admin.edit', ['id' => $model->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        //
    }

}

app/Http/Controllers/Admin/Users/CustomerController.php
<?php

namespace App\Http\Controllers\Admin\Users;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Customer;

class CustomerController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {
        $search = $request->get('search');

        $models = Customer::when($search, function($query) use ($search) {
                    build_like_query($query, 'nama', $search);
                    build_or_like_query($query, 'email', $search);
                    build_or_like_query($query, 'no_telp', $search);
                    build_or_like_query($query, 'alamat', $search);
                })
                ->paginate(10);

        return view('admin.users.customer.index', compact('models'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $model = new Customer();

        return view('admin.users.customer.form', compact('model'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $model = new Customer();

        $validator = \Validator::make($request->all(), [
                    'nama' => 'required',
                    'email' => 'required|email',
                    'password' => 'required',
                    'status' => 'required',
                    'no_telp' => 'required',
                    'alamat' => 'required',
                    'no_id' => 'required',
        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator->errors())->withInput($request->all());
        }

        $model->nama = $request->nama;
        $model->email = $request->email;
        $model->password = bcrypt($request->password);
        $model->status = $request->status;
        $model->no_telp = $request->no_telp;
        $model->alamat  = $request->alamat;
        $model->tipe_id = $request->tipe_id;
        $model->no_id   = $request->no_id;
        $model->status  = $request->status;

        $model->save();

        \Session::flash('success', 'Berhasil menambahkan customer baru');
        return redirect()->route('admin.users.customer.edit', ['id' => $model->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $model = Customer::findOrFail($id);

        return view('admin.users.customer.form', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        $model = Customer::findOrFail($id);

        $validator = \Validator::make($request->all(), [
                    'nama' => 'required',
                    'email' => 'required|email',
                    'status' => 'required',
                    'no_telp' => 'required',
                    'alamat' => 'required',
                    'no_id' => 'required',
        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator->errors())->withInput($request->all());
        }

        $model->nama = $request->nama;
        $model->email = $request->email;
        $model->status = $request->status;
        $model->no_telp = $request->no_telp;
        $model->alamat  = $request->alamat;
        $model->tipe_id = $request->tipe_id;
        $model->no_id   = $request->no_id;
        $model->status  = $request->status;

        if ($request->password)
            $model->password = bcrypt($request->password);

        $model->status = $request->status;

        $model->save();

        \Session::flash('success', 'Berhasil merubah data customer');
        return redirect()->route('admin.users.customer.edit', ['id' => $model->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        //
    }

}

app/Http/Controllers/Admin/Users/MemberController.php
<?php

namespace App\Http\Controllers\Admin\Users;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Member;

class MemberController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {
        $search = $request->get('search');

        $models = Member::when($search, function($query) use ($search) {
                    build_like_query($query, 'nama_pemilik', $search);
                    build_or_like_query($query, 'nama_usaha', $search);
                    build_or_like_query($query, 'email', $search);
                    build_or_like_query($query, 'alamat', $search);
                })
                ->paginate(10);

        return view('admin.users.member.index', compact('models'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $model      = new Member();
        
        return view('admin.users.member.form', compact('model'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $model          = new Member();
        
        $validator      = \Validator::make($request->all(),[
            'nama_usaha'        => 'required',
            'nama_pemilik'      => 'required',
            'no_telp'           => 'required|numeric',
            'kode_pos'          => 'numeric',
            'alamat'            => 'required',
            'tgl_tenggang'      => 'required',
            'id_layanan'        => 'required',
            'email'             => 'required|email|unique:member,email',
            'password'          => 'required',
            'status'            => 'required'
        ]);
        
        if($validator->fails()){
            return redirect()->back()->withErrors($validator->errors())->withInput($request->all());
        }
        
        $model->nama_usaha      = $request->nama_usaha;
        $model->nama_pemilik    = $request->nama_pemilik;
        $model->no_telp         = $request->no_telp;
        $model->kode_pos        = $request->kode_pos;
        $model->alamat          = $request->alamat;
        $model->tgl_tenggang    = $request->tgl_tenggang;
        $model->id_layanan      = $request->id_layanan;
        $model->email           = $request->email;
        $model->password        = bcrypt($request->password);
        $model->status          = $request->status;
        $model->tgl_aktif       = date('Y-m-d H:i:s');
        
        $model->save();
        
        \Session::flash('success', 'Berhasil menambahkan member baru');
        return redirect()->route('admin.users.member.edit', ['id' => $model->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $model          = Member::findOrFail($id);
        
        return view('admin.users.member.form', compact('model'));
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        $model          = Member::findOrFail($id);
        
        $validator      = \Validator::make($request->all(),[
            'nama_usaha'        => 'required',
            'nama_pemilik'      => 'required',
            'no_telp'           => 'required|numeric',
            'kode_pos'          => 'numeric',
            'alamat'            => 'required',
            'tgl_tenggang'      => 'required',
            'id_layanan'        => 'required',
            'email'             => 'required|email',
            'status'            => 'required'
        ]);
        
        if($validator->fails()){
            return redirect()->back()->withErrors($validator->errors())->withInput($request->all());
        }
        
        $model->nama_usaha      = $request->nama_usaha;
        $model->nama_pemilik    = $request->nama_pemilik;
        $model->no_telp         = $request->no_telp;
        $model->kode_pos        = $request->kode_pos;
        $model->alamat          = $request->alamat;
        $model->tgl_tenggang    = $request->tgl_tenggang;
        $model->id_layanan      = $request->id_layanan;
        $model->email           = $request->email;
        $model->status          = $request->status;
        
        if($request->password)
            $model->password        = bcrypt($request->password);
        
        $model->save();
        
        \Session::flash('success', 'Berhasil menyimpan perubahan data member');
        return redirect()->route('admin.users.member.edit', ['id' => $model->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        //
    }

}

resources/views/admin/users/customer/form.blade.php
@extends('layouts.dashboard.admin')

@section('title',$model->exists ? 'Ubah Customer' : 'Tambah Customer')
@section('page-title',$model->exists ? 'Ubah Customer' : 'Tambah Customer')

@section('content')
<div class="block">
    <form action="{{ $model->exists ? route('admin.users.customer.update', ['id' => $model->id]) : route('admin.users.customer.store') }}" method="POST" class="form-horizontal form-bordered">
        {{         csrf_field() }}
        {{ $model->exists ? method_field('PUT') : method_field('POST') }}
        <div class="form-group">
            <label class="col-md-3 control-label">Nama</label>
            <div class="col-md-9">
                <input type="text" name="nama" class="form-control" value="{{ old('nama', $model->nama) }}" placeholder="Nama">
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Email</label>
            <div class="col-md-9">
                <input type="text" name="email" class="form-control" value="{{ old('email', $model->email) }}" placeholder="Email">
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Password</label>
            <div class="col-md-9">
                <input type="password" name="password" class="form-control" value="">
                @if($model->exists)
                <span class="help-block">Kosongkan password jika tidak ingin diganti</span>
                @endif
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">No Telp.</label>
            <div class="col-md-9">
                <input type="number" name="no_telp" value="{{old('no_telp', $model->no_telp) }}" class=" form-control" placeholder="No Telp.">
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Alamat</label>
            <div class="col-md-9">
                <input type="text" class=" form-control" value="{{old('alamat', $model->alamat) }}"  name="alamat" placeholder="Alamat">
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Tipe identitas</label>
            <div class="col-md-9">
                <select name="tipe_id" class="form-control">
                    <option value="KTP" {{ old('tipe_id', $model->tipe_id) == 'KTP' ? 'selected' : null }}>KTP</option>
                    <option value="SIM" {{ old('tipe_id', $model->tipe_id) == 'SIM' ? 'selected' : null }} >SIM</option>
                    <option value="PASPORT" {{ old('tipe_id', $model->tipe_id) == 'PASPORT' ? 'selected' : null }}>PASPORT</option>
                    <option value="KITAS" {{ old('tipe_id', $model->tipe_id) == 'KITAS' ? 'selected' : null }}>KITAS</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">No Identitas</label>
            <div class="col-md-9">
                <input type="text" class=" form-control" name="no_id" placeholder="No Identitas" value="{{old('no_id', $model->no_id) }}" >
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Status</label>
            <div class="col-md-9">
                <select name="status" class="form-control">
                    <option value="0" {{ old('status', $model->status) == 0 ? 'selected' : null }} >Tidak aktif</option>
                    <option value="1" {{ old('status', $model->status) == 1 ? 'selected' : null }}>Aktif</option>
                </select>
            </div>
        </div>
        <div class="form-group form-actions">
            <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-sm btn-primary">
                    <i class="fa fa-angle-right"></i> 
                    Submit
                </button>
            </div>
        </div>
    </form>
</div>


@endsection

resources/views/admin/users/customer/index.blade.php
@extends('layouts.dashboard.admin')

@section('title', 'User Customer')
@section('page-title', 'User Customer')

@section('content')
<div class="block">
    <div class="row mb15">
        <div class="col-md-6">
            <a href="{{ route('admin.users.customer.create') }}" class="btn btn-warning">
                <i class="gi gi-plus"></i>
                Tambah Customer
            </a>
        </div>
        <div class="col-md-6">
            <form class="form-inline" action="{{ route('admin.users.customer.index') }}">
                <div  class="dataTables_filter">
                    <label>
                        <div class="input-group">
                            <input type="search" name="search" value="{{ Request::get('search') }}" class="form-control" aria-controls="example-datatable" placeholder="Cari...">
                            <span class="input-group-addon"><i class="fa fa-search"></i></span>
                        </div>
                    </label>
                </div>
            </form>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-hover table-striped table-condensed">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nama</th>
                    <th>Email</th>
                    <th>Status</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach($models as $key => $model)
                <tr>
                    <td>{{ ($models->perPage() * ($models->currentPage() - 1)) + ($key + 1)}}</td>
                    <td>{{ $model->nama }}</td>
                    <td>{{ $model->email }}</td>
                    <td>{{ $model->status ? 'Aktif' : 'Tidak Aktif'}}</td>
                    <td class="text-right">
                        <div class="btn-group btn-group-xs">
                            <a href="{{ route('admin.users.customer.edit', ['id' => $model->id]) }}" data-toggle="tooltip" title="" class="btn btn-default" data-original-title="Edit"><i class="fa fa-pencil"></i></a>
                        </div>
                    </td>
                </tr>
                @endforeach

                @if($models->count() == 0)
                <tr>
                    <td colspan="5">
                        <i>Tidak ada data untuk ditampilkan</i>
                    </td>
                </tr>
                @endif
            </tbody>
        </table>
    </div>
    
    {!! $models->appends(['search' => Request::get('search')])->links() !!}
</div>
@endsection