routes/admin.php
<?php

/*
  |--------------------------------------------------------------------------
  | ADMIN Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */
Route::group(['namespace' => 'Auth', 'prefix' => 'auth'], function() {
    Route::get('login', 'LoginController@showLoginForm')->name('auth.login');
    Route::post('login', 'LoginController@login')->name('auth.login');
    Route::get('logout', 'LoginController@logout')->name('auth.logout');
});

Route::group(['middleware' => 'auth.admin'], function() {
    Route::get('/', 'DashboardController@index')->name('dashboard');


    Route::resource('layanan', 'LayananController');
    Route::resource('wilayah', 'WilayahController');
    Route::resource('transaksi', 'TransaksiController');
    Route::group(['as' => 'users.', 'namespace' => 'Users', 'prefix' => 'users'], function() {
        Route::resource('admin', 'AdminController' ,[]);
        Route::resource('member', 'MemberController' ,[]);
        Route::resource('customer', 'CustomerController' ,[]);
    });
});

routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', 'HomeController@index')->name('home');
Route::get('search', 'TourController@search')->name('search');


Route::get('tour/{id}', 'TourController@detail')->name('tour');
Route::get('pesan', 'TourController@pesan')->name('pesan');
Route::post('pesan', 'TourController@proses')->name('pesan');
Route::get('pesan/bayar/{id}', 'TourController@konfirmasi')->name('bayar');
Route::post('pesan/bayar/{id}', 'TourController@bayar')->name('bayar');

Route::get('profil/pesanan', 'ProfileController@pesanan')->name('mybooking');
Route::get('profile/setting', 'ProfileController@setting')->name('mysetting');
Route::post('profile/setting', 'ProfileController@simpan')->name('save_profile');

Route::auth();
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

app/Http/Controllers/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller {
    
    public function index(){
        return view('admin.dashboard.index');
    }
}

app/Http/Controllers/Member/DashboardController.php
<?php

namespace App\Http\Controllers\Member;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller {

    //
    public function index() {
        
        return view('member.dashboard.index');
    }

}

resources/views/layouts/dashboard/menu/admin.blade.php
<!-- Sidebar Navigation -->
<ul class="sidebar-nav">
    <li>
        <a href="{{ route('admin.dashboard') }}"><i class="gi gi-stopwatch sidebar-nav-icon"></i>Dashboard</a>
    </li>
    <li class="divider"></li>
    <li>
        <a href="{{ route('admin.transaksi.index') }}"><i class="gi gi-money sidebar-nav-icon"></i>Transaksi Member</a>
    </li>
    <li class="divider"></li>
    <li>
        <a href="{{ route('admin.layanan.index') }}"><i class="gi gi-adjust sidebar-nav-icon"></i>Layanan</a>
    </li>
    <li class="sidebar-header">
        <span class="sidebar-header-title">Wilayah</span>
    </li>
    <li>
        <a href="{{ route('admin.wilayah.index') }}"><i class="gi gi-globe sidebar-nav-icon"></i>Daftar Wilayah</a>
    </li>
    <li>
        <a href="{{ route('admin.wilayah.create') }}"><i class="gi gi-plus sidebar-nav-icon"></i>Tambah Wilayah</a>
    </li>
    <li class="sidebar-header">
        <span class="sidebar-header-title">Users</span>
    </li>
    <li>
        <a href="{{ route('admin.users.admin.index') }}"><i class="gi gi-lock sidebar-nav-icon"></i>Administrator</a>
    </li>
    <li>
        <a href="{{ route('admin.users.member.index') }}"><i class="gi gi-user_add sidebar-nav-icon"></i>Member</a>
    </li>
    <li>
        <a href="{{ route('admin.users.customer.index') }}"><i class="gi gi-user sidebar-nav-icon"></i>Customer</a>
    </li>
</ul>
<!-- END Sidebar Navigation -->

resources/views/layouts/dashboard/menu/member.blade.php
<div class="sidebar-section sidebar-user clearfix sidebar-nav-mini-hide" style="padding-left:0px; text-align:center">
    <div style="font-size:22px;">
        {{ Auth::guard('member')->user()->layanan->nama }}
    </div>
    <div>
        <small>Berlaku sampai</small> <br />
        {{ Auth::guard('member')->user()->tgl_tenggang }}
    </div>

</div>
<!-- Sidebar Navigation -->
<ul class="sidebar-nav">
    <li>
        <a href="{{ route('member.dashboard') }}"><i class="gi gi-stopwatch sidebar-nav-icon"></i>Dashboard</a>
    </li>
    <li class="divider"></li>
    <li>
        <a href="{{ route('member.pemesanan.index') }}"><i class="gi gi-book_open sidebar-nav-icon"></i>Pemesanan</a>
    </li>
    <li class="sidebar-header">
        <span class="sidebar-header-title">Tour</span>
    </li>
    <li>
        <a href="{{ route('member.tour.index') }}"><i class="gi gi-bicycle sidebar-nav-icon"></i>Daftar Tour</a>
    </li>
    <li>
        <a href="{{ route('member.tour.create') }}"><i class="gi gi-plus sidebar-nav-icon"></i>Tambah Tour</a>
    </li>
    <li class="sidebar-header">
        <span class="sidebar-header-title">Bank</span>
    </li>
    <li>
        <a href="{{ route('member.bank.index') }}"><i class="gi gi-bank sidebar-nav-icon"></i>Daftar Bank</a>
    </li>
    <li>
        <a href="{{ route('member.bank.create') }}"><i class="gi gi-plus sidebar-nav-icon"></i>Tambah Bank</a>
    </li>
</ul>
<!-- END Sidebar Navigation -->