routes/admin.php
<?php

/*
  |--------------------------------------------------------------------------
  | ADMIN Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */
Route::group(['namespace' => 'Auth', 'prefix' => 'auth'], function() {
    Route::get('login', 'LoginController@showLoginForm')->name('auth.login');
    Route::post('login', 'LoginController@login')->name('auth.login');
    Route::get('logout', 'LoginController@logout')->name('auth.logout');
});

Route::group(['middleware' => 'auth.admin'], function() {
    Route::get('/', 'DashboardController@index')->name('dashboard');


    Route::resource('layanan', 'LayananController');
    Route::resource('wilayah', 'WilayahController');
    Route::resource('transaksi', 'TransaksiController');
    Route::group(['as' => 'users.', 'namespace' => 'Users', 'prefix' => 'users'], function() {
        Route::resource('admin', 'AdminController' ,[]);
        Route::resource('member', 'MemberController' ,[]);
        Route::resource('customer', 'CustomerController' ,[]);
    });
});

routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', 'HomeController@index')->name('home');
Route::get('search', 'TourController@search')->name('search');


Route::get('tour/{id}', 'TourController@detail')->name('tour');
Route::get('pesan', 'TourController@pesan')->name('pesan');
Route::post('pesan', 'TourController@proses')->name('pesan');
Route::get('pesan/bayar/{id}', 'TourController@konfirmasi')->name('bayar');
Route::post('pesan/bayar/{id}', 'TourController@bayar')->name('bayar');

Route::get('profil/pesanan', 'ProfileController@pesanan')->name('mybooking');
Route::get('profile/setting', 'ProfileController@setting')->name('mysetting');
Route::post('profile/setting', 'ProfileController@simpan')->name('save_profile');

Route::auth();
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

app/Wilayah.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Wilayah extends Model {

    protected $table = 'wilayah';

}

app/Http/Controllers/Admin/WilayahController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Wilayah;

class WilayahController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {
        $search = $request->get('search');

        $models = Wilayah::orderBy('nama','asc')
                ->when($search, function($query) use ($search) {
                    build_like_query($query, 'nama', $search);
                })
                ->paginate(10);

        return view('admin.wilayah.index', compact('models'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $model = new Wilayah();

        return view('admin.wilayah.form', compact('model'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $validator = \Validator::make($request->all(), [
                    'nama' => 'required',
                    ], [
                    'nama.required' => 'Nama wilayah harus diisi',
        ]);

        if ($validator->fails()) {
            return redirect()->back()->withInput($request->all())->withErrors($validator->errors());
        }

        $model = new Wilayah();
        $model->nama = $request->nama;

        $model->save();

        \Session::flash('success', 'Data wilayah berhasil ditambahkan');
        return redirect()->route('admin.wilayah.edit', ['id' => $model->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $model = Wilayah::findOrFail($id);

        return view('admin.wilayah.form', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        $validator = \Validator::make($request->all(), [
                    'nama' => 'required',
                    ], [
                    'nama.required' => 'Nama wilayah harus diisi',
        ]);

        if ($validator->fails()) {
            return redirect()->back()->withInput($request->all())->withErrors($validator->errors());
        }

        $model = Wilayah::findOrFail($id);
        $model->nama = $request->nama;

        $model->save();

        \Session::flash('success', 'Data wilayah berhasil disimpan');
        return redirect()->route('admin.wilayah.edit', ['id' => $model->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        //
    }

}

resources/views/admin/wilayah/form.blade.php
@extends('layouts.dashboard.admin')

@section('title', $model->exists ? 'Ubah Wilayah' : 'Tambah Wilayah')
@section('page-title',$model->exists ? 'Ubah Wilayah' : 'Tambah Wilayah')


@section('content')
<div class="block">
    <form action="{{ $model->exists ? route('admin.wilayah.update', ['id' => $model->id]) : route('admin.wilayah.store') }}" method="POST" class="form-horizontal form-bordered">
        {{         csrf_field() }}
        {{ $model->exists ? method_field('PUT') : method_field('POST') }}
        <div class="form-group">
            <label class="col-md-3 control-label">Nama Wilayah</label>
            <div class="col-md-9">
                <input type="text" name="nama" class="form-control" value="{{ old('nama', $model->nama) }}">
            </div>
        </div>
        <div class="form-group form-actions">
            <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-sm btn-primary">
                    <i class="fa fa-angle-right"></i> 
                    Submit
                </button>
            </div>
        </div>
    </form>
</div>


@endsection

resources/views/admin/wilayah/index.blade.php
@extends('layouts.dashboard.admin')

@section('title', 'Daftar Wilayah')
@section('page-title', 'Daftar Wilayah')

@section('content')
<div class="block">
    <div class="row mb15">
        <div class="col-md-6">
            <a href="{{ route('admin.wilayah.create') }}" class="btn btn-warning">
                <i class="gi gi-plus"></i>
                Tambah Wilayah
            </a>
        </div>
        <div class="col-md-6">
            <form class="form-inline" action="{{ route('admin.wilayah.index') }}">
                <div  class="dataTables_filter">
                    <label>
                        <div class="input-group">
                            <input type="search" name="search" value="{{ Request::get('search') }}" class="form-control" aria-controls="example-datatable" placeholder="Cari...">
                            <span class="input-group-addon"><i class="fa fa-search"></i></span>
                        </div>
                    </label>
                </div>
            </form>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-hover table-striped table-condensed">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nama Wilayah</th>
                    <th>Dibuat</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach($models as $key => $model)
                <tr>
                    <td>{{ ($models->perPage() * ($models->currentPage() - 1)) + ($key + 1)}}</td>
                    <td>
                        <div class=""><strong>{{ $model->nama }}</strong></div> 
                    </td>
                    <td>{{ date('d F Y', strtotime($model->created_at)) }}</td>
                    <td class="text-right">
                        <div class="btn-group btn-group-xs">
                            <a href="{{ route('admin.wilayah.edit', ['id' => $model->id]) }}" data-toggle="tooltip" title="" class="btn btn-default" data-original-title="Edit"><i class="fa fa-pencil"></i></a>
                        </div>
                    </td>
                </tr>
                @endforeach

                @if($models->count() == 0)
                <tr>
                    <td colspan="4">
                        <i>Tidak ada data untuk ditampilkan</i>
                    </td>
                </tr>
                @endif
            </tbody>
        </table>

        {!! $models->appends(['search' => Request::get('search')])->links() !!}
    </div>
</div>
@endsection